name: Build and Push to GHCR

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (main)
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/unraid-docker-webui:latest

      - name: Build and push Docker image (develop)
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/develop'
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/unraid-docker-webui:develop